/* Water Lab — dedicated water tools, progressive physics settings and Particle Flow. */
(() => {
  const esc=v=>String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  function boot(){
    const api=window.__cerebraS9,s=api&&api.studio;if(!api||!api.ready||!s){setTimeout(boot,180);return}if(api.uiReady)return;
    const css=document.createElement('style');css.textContent=`
      #studio .st-s9-panel{--water-accent:#b597ff;position:absolute;z-index:65;right:12px;top:12px;width:min(350px,calc(100vw - 24px));max-height:calc(100dvh - 100px);overflow:auto;overflow-x:hidden;overscroll-behavior:contain;padding:16px;border-radius:24px;pointer-events:auto;scrollbar-width:thin;background:linear-gradient(155deg,#30263bf5,#191722f5);box-shadow:0 18px 60px #0005;border:1px solid #b6caff35;color:#edf3ff}
      #studio .st-s9-panel[hidden],#studio .st-water-active[hidden],#studio .st-water-pad[hidden],#studio .st-s9-panel [hidden]{display:none!important}
      #studio .st-water-pad{position:absolute;inset:0;z-index:5;touch-action:none;cursor:crosshair;pointer-events:auto}
      /* Keep canvas input beneath every Studio control, including a folded dock. */
      #studio .st-dock,#studio .st-rail,#studio .st-back,#studio .st-zoom,#studio .studio-panel,#studio .st-context,#studio .st-fly,#studio .st-save{z-index:30}
      #studio .st-water-active{position:absolute;z-index:41;left:50%;bottom:90px;transform:translateX(-50%);display:flex;align-items:center;gap:12px;padding:8px 10px 8px 16px;max-width:calc(100vw - 28px);border-radius:30px;font:12px var(--f-sans);pointer-events:auto;white-space:nowrap}
      #studio .st-water-active button{border:0;border-radius:20px;background:#95dcff;color:#10212e;font:600 12px var(--f-sans);min-height:38px;padding:0 16px}
      #studio .st-water-quick{position:absolute;z-index:42;left:140px;top:90px;width:132px;max-height:calc(100dvh - 195px);overflow:auto;overscroll-behavior:contain;pointer-events:auto;padding:8px;border:1px solid #b597ff50;border-radius:22px;background:linear-gradient(155deg,#30263bf2,#191722f2);box-shadow:0 10px 30px #0005;scrollbar-width:none}
      #studio .st-water-quick[hidden]{display:none!important}#studio .st-water-quick .st-water-tools{grid-template-columns:repeat(2,minmax(0,1fr));margin:6px 0}#studio .st-water-quick .st-water-tools button{min-height:48px;font-size:9px}#studio .st-water-quick .st-water-palette{justify-content:center;margin-top:8px}#studio .st-water-quick .st-water-swatch{width:32px;height:32px;border-radius:50%;border:2px solid #ffffff60;background:var(--swatch);padding:0}#studio .st-water-quick .st-water-swatch[aria-pressed=true]{outline:2px solid #b597ff;outline-offset:2px}#studio .st-water-quick input[type=color]{width:32px;height:34px;border:0;background:transparent}#studio .st-water-quick>b{font:600 11px var(--f-cond);letter-spacing:.08em}#studio .st-water-quick [data-water-lab]{width:100%;min-height:36px;text-align:center;padding:8px 10px;line-height:1.35;border:1px solid #b597ff50;border-radius:10px;background:#b597ff20;color:#ede4ff;margin-top:8px}
      #studio .st-water-quick .st-water-quick-sliders{display:grid;gap:0 10px}
      #studio .st-water-quick .st-water-row{font:11px var(--f-cond);gap:4px;margin:8px 0 0}#studio .st-water-quick .st-water-row input[type=range]{min-height:32px;margin:0;touch-action:pan-y}
      body #studio .st-dock .st-btn.is-sel,body #studio .st-dock .st-group>.st-btn.is-sel,body #studio .st-dock .st-group.is-open>.st-btn{background:#edf0f7!important;color:#171b23!important;border-color:#edf0f7!important}
      #studio .st-dock .st-btn.is-sel :is(span,svg,i){color:inherit}
      /* Decorative rim must stay behind lifted buttons, without clipping popovers. */
      #studio .st-dock.mb::before,#studio .st-dock.mb::after{display:none}
      #studio .st-dock>.st-btn,#studio .st-dock>.st-group,#studio .st-dock>select{position:relative;z-index:2}
      #studio .st-dock>.st-btn:not(.is-sel),#studio .st-dock>.st-group:not(.is-open)>.st-btn{background:#292c38!important}
      #studio .st-water-palette label{display:grid;justify-items:center;gap:3px;font:9px var(--f-cond);color:#c9bbdf}
      #studio .st-water-head{position:sticky;top:-16px;z-index:2;background:#30263b;padding:12px 0;display:flex;align-items:center;gap:12px;margin-bottom:12px}#studio .st-water-head>div{flex:1}#studio .st-water-head b{font:600 18px var(--f-cond);letter-spacing:.06em}#studio .st-water-head small{display:block;font:11px var(--f-sans);color:#9eb1cd;margin-top:4px}#studio .st-water-head button{width:40px;height:40px;border:1px solid #ffffff24;border-radius:50%;background:#ffffff0a;color:inherit;font-size:24px}
      #studio .st-water-tools{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:12px 0}
      #studio .st-water-tools button{min-width:0;min-height:64px;border:1px solid #ffffff20;border-radius:14px;background:#ffffff08;color:#c4d3e9;display:grid;place-content:center;gap:5px;font:600 10px var(--f-cond);letter-spacing:.04em}
      #studio .st-water-tools button span{font:21px var(--f-sans);line-height:1}#studio .st-water-tools button.is-on{background:linear-gradient(135deg,#268cce,#726de3);color:#fff;border-color:#a2cfff80;box-shadow:0 4px 14px #168fff20}
      #studio .st-water-row{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:6px 12px;margin:11px 0;font:12px var(--f-sans);color:#d0def2}
      #studio .st-water-row input[type=range]{grid-column:1/-1;width:100%;accent-color:#b597ff;min-height:24px}#studio .st-water-row output{font:11px var(--f-mono);color:#c5afff}#studio .st-water-row select{max-width:165px;min-width:0;border-radius:9px;padding:8px;background:#293344;color:#edf3ff;border:1px solid #ffffff20;font:11px var(--f-sans)}#studio .st-water-row input[type=color]{width:44px;height:38px;background:transparent;border:0}#studio .st-water-row input[type=checkbox]{width:20px;height:20px;accent-color:#85cfff}
      #studio .st-water-section{border:1px solid #ffffff20;border-radius:18px;background:#ffffff04;margin-top:12px;padding:6px 12px}#studio .st-water-section summary{min-height:44px;cursor:pointer;display:flex;align-items:center;justify-content:space-between;font:600 13px var(--f-cond);letter-spacing:.05em;color:#e4eefe}#studio .st-water-section summary:after{content:'+';color:#c5afff;font-size:20px}#studio .st-water-section[open] summary:after{content:'−'}
      #studio .st-water-actions{display:flex;gap:8px;margin-top:15px}#studio .st-water-actions button{display:flex;align-items:center;justify-content:center;text-align:center;padding:10px 12px;line-height:1.35;flex:1;min-width:0;min-height:42px;border:1px solid #ffffff25;background:#ffffff08;color:#c8d7ee;border-radius:12px;font:11px var(--f-sans)}#studio .st-water-note{font:11px/1.5 var(--f-sans);color:#95a9c5;margin:8px 0}#studio .st-water-error{font:12px/1.5 var(--f-sans);color:#ffacac}#studio .st-water-palette{display:flex;gap:6px;flex-wrap:wrap}
      @media(max-width:700px){#studio .st-water-quick .st-water-quick-sliders{grid-template-columns:repeat(3,minmax(0,1fr))}#studio .st-water-quick{top:auto!important;left:8px!important;right:8px;bottom:150px;width:auto;max-height:min(220px,32dvh);padding:8px 10px;border-radius:18px}#studio .st-water-quick .st-water-tools{display:flex;overflow:auto;gap:6px;scrollbar-width:none}#studio .st-water-quick .st-water-tools button{flex:0 0 58px;min-height:48px}#studio .st-water-quick>b{display:none}#studio .st-water-quick .st-water-palette{display:inline-flex;vertical-align:middle;margin:4px 8px 0 0}#studio .st-water-quick [data-water-lab]{width:auto;min-height:32px;padding:0 10px;margin:4px 0 0}#studio .st-s9-panel{top:auto;bottom:84px;right:8px;width:calc(100vw - 16px);max-height:55dvh;padding:14px;border-radius:24px}#studio .st-water-tools button{min-height:60px}#studio .st-water-row select{min-height:40px}#studio .st-water-row input[type=range]{min-height:32px}}
      /* Match Studio's 44px switch rail: its 18px thumb must fit when ON. */
      #studio .st-water-row input[type=checkbox]{width:44px;min-width:44px;height:26px;justify-self:end}
      #studio .st-water-head>div{min-width:0}#studio .st-water-head button{display:grid;place-items:center;flex:0 0 40px;padding:0;line-height:1}
      #studio .st-water-head button svg{width:20px;height:20px;display:block;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round}
      #studio .st-water-row>span{min-width:0;overflow-wrap:anywhere}#studio .st-water-row select{max-width:100%;width:156px}
      #studio .st-water-transport{position:sticky;bottom:-16px;padding:10px 0;background:#211d2d;z-index:2;border-top:1px solid #ffffff20}
    `;document.head.append(css);
    const row=(key,label,min,max,step=1)=>`<label class="st-water-row"><span>${label}</span><output data-water-output="${key}"></output><input type="range" data-water="${key}" min="${min}" max="${max}" step="${step}"></label>`;
    const toggle=(key,label)=>`<label class="st-water-row"><span>${label}</span><input type="checkbox" data-water="${key}"></label>`;
    const select=(key,label,options)=>`<label class="st-water-row"><span>${label}</span><select data-water="${key}">${options.map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></label>`;
    const section=(title,body,extra='')=>`<details class="st-water-section" ${extra}><summary>${title}</summary>${body}</details>`;
    const tools=[['paint','⌁','Water pen'],['drop','●','Place water'],['ripple','◎','Ripple'],['pour','↓','Pour'],['tentacle','〰','Water ribbon'],['stretch','↔','Push / pull'],['eraser','◌','Eraser'],['picker','◇','Pick colour']];
    const panel=document.createElement('section');panel.className='st-s9-panel';panel.hidden=true;panel.setAttribute('aria-label','Water Lab');panel.innerHTML=`
      <header class="st-water-head"><div><b>Water Lab</b><small>Flow, ripples &amp; particles</small></div><button type="button" data-s9-close aria-label="Close Water Lab"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5l14 14M19 5L5 19"/></svg></button></header>
      <div class="st-water-tools">${tools.map(([k,i,n])=>`<button type="button" data-water-tool="${k}" aria-pressed="false"><span aria-hidden="true">${i}</span>${n}</button>`).join('')}</div>
      <div class="st-water-actions"><button type="button" data-water-nava>Nava flow · soft colour pools</button></div>
      <p class="st-water-note">Choose a tool, then draw on the canvas. Water tools are separate from Studio drawing.</p><p class="st-water-error" hidden></p>
      <label class="st-water-row"><span>Water colour</span><input type="color" data-water-colour></label>${row('brushSize','Brush size',.2,3,.1)}
      ${toggle('on','Show water')}${toggle('paused','Freeze water')}
      ${section('Composition',select('layer','Water layer',[['front','In front of Cerebra'],['back','Behind Cerebra']])+toggle('collision','Collide with 3D surface')+`<div data-water-show="collision">${row('collisionBounce','Impact bounce',0,1,.05)+row('collisionSpread','Splash spread',0,2,.05)+row('collisionStick','Surface adhesion',0,1,.05)+row('collisionStain','Stain opacity',0,1,.05)+row('stainSpread','Stain coverage',0,2,.05)+row('stainLifetime','Stain lifetime · 0 = permanent',0,120,5)}<p class="st-water-note">Water flows around the selected 3D surface. Stains follow the surface as it moves and rotates.</p><div class="st-water-actions"><button type="button" data-water-stains-clear>Clear surface stains</button></div></div>`,'open')}
      ${section('Water appearance',row('opacity','Opacity',.1,1,.05)+row('wispiness','Edge sharpness',1,10)+row('clarity','Clarity',1,5,.1)+row('glow','Water brightness',0,5,.1)+toggle('gradientBrush','Gradient brush')+`<div data-water-show="gradientBrush">${row('gradientSpeed','Colour speed',1,10)}</div>`)}
      ${section('Water physics',row('viscosity','Viscosity',.01,1,.01)+row('dissipation','Colour retention',.97,1,.0001)+row('curl','Vorticity',0,50)+row('timeScale','Flow speed',.1,2,.1)+toggle('realWater','Surface tension')+`<div data-water-show="realWater">${row('cohesion','Cohesion',0,10)+row('splash','Splash strength',0,10)}</div>`+toggle('canvasFrame','Contain water at canvas edges'))}
      ${section('Current & brush motion',toggle('flowEnabled','Ambient current')+`<div data-water-show="flowEnabled">${row('flowSpeed','Current speed',1,10)+select('direction','Direction',[['right','Right'],['left','Left'],['up','Up'],['down','Down'],['ne','Up-right'],['nw','Up-left'],['se','Down-right'],['sw','Down-left']])}</div>`+select('motion','Stroke motion',[['normal','Natural'],['spin','Spin'],['zigzag','Zigzag'],['wave','Wave'],['radial','Radial']])+row('symmetry','Radial copies',1,12)+toggle('mirror','Mirror stroke')+`<div data-water-show="tentacle">${row('tentacleLength','Ribbon length',5,15)+row('tentacleSway','Ribbon sway',0,10)}</div>`+`<div class="st-water-actions"><button type="button" data-water-stop>Stop water</button><button type="button" data-water-motion-reset>Reset motion</button></div>`)}
      ${section('Particle Flow',toggle('particles','Show particles')+`<div data-water-show="particles">${row('particleCount','Count',50,1200,50)+row('particleSpeed','Speed',1,10)+row('particleSize','Size',.5,6,.1)+row('particleAlpha','Opacity',10,100)+row('particleTrail','Trails',0,10)+select('particleInteract','Water interaction',[['none','Free flow'],['absorb','Absorb colour'],['deposit','Deposit colour'],['bounce','Bounce'],['carry','Carry colour'],['charged','Charged'],['sph','SPH fluid']])+row('particleInteractAmt','Interaction strength',1,10)+row('particleColorCount','Palette colours',1,5)}<div class="st-water-palette">${Array.from({length:5},(_,i)=>`<input type="color" data-water-palette="${i}" aria-label="Particle colour ${i+1}">`).join('')}</div></div>`)}
      <div class="st-water-actions"><button type="button" data-water-clear>Clear water &amp; particles</button><button type="button" data-water-reset>Reset Lab</button></div><p class="st-water-note">Undo / Redo and Studio Save include your water composition.</p><div class="st-water-actions st-water-transport"><button type="button" data-water-freeze>Pause water</button><button type="button" data-water-resume>Resume water</button></div>`;
    s.el.append(panel);
    const quick=document.createElement('section');quick.className='st-water-quick';quick.hidden=true;quick.setAttribute('aria-label','Water Lab canvas tools');
    quick.innerHTML=`<b>WATER LAB</b><div class="st-water-tools">${tools.map(([k,i,n])=>`<button type="button" data-water-tool="${k}" aria-label="${n}" aria-pressed="false"><span aria-hidden="true">${i}</span>${n}</button>`).join('')}</div><div class="st-water-palette">${Array.from({length:3},(_,i)=>`<label><button type="button" class="st-water-swatch" data-water-slot="${i}" aria-label="Use water colour ${i+1}"></button><input type="color" data-water-slot-edit="${i}" aria-label="Edit water colour ${i+1}"></label>`).join('')}</div><div class="st-water-quick-sliders">${row('brushSize','Brush size',.2,3,.1)}${row('timeScale','Flow speed',.1,2,.1)}${row('viscosity','Viscosity',.01,1,.01)}</div><button type="button" data-water-lab>Water settings</button>`;
    s.el.append(quick);
    quick.querySelectorAll('[data-water-tool]').forEach(b=>b.onclick=()=>api.activate(true,b.dataset.waterTool));
    quick.querySelectorAll('[data-water-slot]').forEach(b=>b.onclick=()=>api.change('brushColor',api.clone(api.get().waterColors[+b.dataset.waterSlot]),true));
    quick.querySelectorAll('[data-water-slot-edit]').forEach(el=>el.onchange=()=>{const colors=api.clone(api.get().waterColors),c=rgb(el.value);colors[+el.dataset.waterSlotEdit]=c;api.change('waterColors',colors);api.change('brushColor',c,true)});
    quick.querySelector('[data-water-lab]').onclick=()=>{s.closeStudioMenus&&s.closeStudioMenus('lab');panel.hidden=false};
    const layoutQuick=()=>{if(innerWidth<=700)return;const rails=[...s.el.querySelectorAll('.st-rail')].map(el=>el.getBoundingClientRect()).filter(r=>r.width&&r.left<innerWidth*.4);quick.style.left=Math.min(innerWidth-144,Math.max(62,...rails.map(r=>r.right))+8)+'px';quick.style.top=Math.max(80,Math.min(...rails.map(r=>r.top),90))+'px'};
    addEventListener('resize',layoutQuick);layoutQuick();
    panel.querySelector('[data-s9-close]').onclick=()=>panel.hidden=true;
    const hex=rgb=>'#'+rgb.map(v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0')).join(''),rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));
    const dirs={right:{x:1,y:0},left:{x:-1,y:0},up:{x:0,y:1},down:{x:0,y:-1},ne:{x:.707,y:.707},nw:{x:-.707,y:.707},se:{x:.707,y:-.707},sw:{x:-.707,y:-.707}};
    api.onSync=()=>{const st=api.get();quick.hidden=!api.active;quick.querySelectorAll('[data-water-slot]').forEach(b=>{const c=st.waterColors[+b.dataset.waterSlot];b.style.setProperty('--swatch',hex(c));b.setAttribute('aria-pressed',String(hex(c)===hex(st.brushColor)))});quick.querySelectorAll('[data-water-slot-edit]').forEach(el=>el.value=hex(st.waterColors[+el.dataset.waterSlotEdit]));quick.querySelectorAll('[data-water-tool]').forEach(b=>{const on=b.dataset.waterTool===st.tool;b.classList.toggle('is-on',on);b.setAttribute('aria-pressed',String(on))});layoutQuick();[...quick.querySelectorAll('[data-water]'),...panel.querySelectorAll('[data-water]')].forEach(el=>{const k=el.dataset.water;if(k==='direction'){el.value=Object.keys(dirs).find(key=>dirs[key].x===st.flowDir.x&&dirs[key].y===st.flowDir.y)||'right'}else if(el.type==='checkbox')el.checked=!!st[k];else el.value=st[k]});[...quick.querySelectorAll('[data-water-output]'),...panel.querySelectorAll('[data-water-output]')].forEach(el=>el.textContent=String(api.get()[el.dataset.waterOutput]));
      panel.querySelector('[data-water-freeze]').hidden=st.paused;panel.querySelector('[data-water-resume]').hidden=!st.paused;

      panel.querySelector('[data-water-colour]').value=hex(st.brushColor);panel.querySelectorAll('[data-water-tool]').forEach(b=>{const on=api.active&&b.dataset.waterTool===st.tool;b.classList.toggle('is-on',on);b.setAttribute('aria-pressed',String(on))});
      panel.querySelectorAll('[data-water-show]').forEach(el=>el.hidden=el.dataset.waterShow==='tentacle'?st.tool!=='tentacle':!st[el.dataset.waterShow]);
      panel.querySelectorAll('[data-water-palette]').forEach(el=>{const i=+el.dataset.waterPalette;el.hidden=i>=st.particleColorCount;el.value=hex(st.particleColors[i]||st.brushColor)});const error=panel.querySelector('.st-water-error');error.hidden=!api.error;error.textContent=api.error||'';
    };
    panel.querySelectorAll('[data-water-tool]').forEach(b=>b.onclick=()=>api.activate(true,b.dataset.waterTool));
    [...panel.querySelectorAll('[data-water]'),...quick.querySelectorAll('[data-water]')].forEach(el=>{const apply=commit=>{const key=el.dataset.water,value=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;api.change(key==='direction'?'flowDir':key,key==='direction'?dirs[value]:value,commit)};el.addEventListener('input',()=>apply(false));el.addEventListener('change',()=>apply(true))});
    const colour=panel.querySelector('[data-water-colour]');colour.oninput=()=>api.change('brushColor',rgb(colour.value));colour.onchange=()=>api.change('brushColor',rgb(colour.value),true);
    panel.querySelectorAll('[data-water-palette]').forEach(el=>el.onchange=()=>{const colors=api.clone(api.get().particleColors);colors[+el.dataset.waterPalette]=rgb(el.value);api.change('particleColors',colors,true)});
    panel.querySelector('[data-water-stains-clear]').onclick=()=>{api.collision.clear();s.commit()};
    panel.querySelector('[data-water-stop]').onclick=()=>api.stopFlow();panel.querySelector('[data-water-motion-reset]').onclick=api.resetMotion;panel.querySelector('[data-water-clear]').onclick=api.clear;panel.querySelector('[data-water-reset]').onclick=()=>{api.set(api.DEF);s.commit()};
    panel.querySelector('[data-water-nava]').onclick=api.navaFlow;
    panel.querySelector('[data-water-freeze]').onclick=()=>api.stopFlow();panel.querySelector('[data-water-resume]').onclick=()=>api.change('paused',false,true);
    api.uiReady=true;api.onSync();
  }
  boot();
})();
