/* Launch paths and a searchable field guide. Read the live UI/registries; never clone interactive controls. */
(() => {
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const arrow = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
  const book = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v15M3 4c4-1 7 0 9 2 2-2 5-3 9-2v15c-4-1-7 0-9 2-2-2-5-3-9-2Z"/></svg>';
  const orbit = '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="6"/><ellipse cx="12" cy="12" rx="12" ry="4" transform="rotate(-35 12 12)"/></svg>';
  const chapters = [['start','Start here'],['tools','Tools'],['design','Design & Kits'],['tune','Tune the core'],['effects','Effects'],['water','Water Lab'],['layers','Layers & motion'],['save','Save & export'],['menus','Menu bar']];
  const intros = {
    start:['The Studio workspace','เลือกดาวหรือใช้ Cerebra เป็นจุดเริ่มต้น แล้วจัดภาพด้วยข้อความ รูปทรง และเอฟเฟกต์ ก่อนบันทึกงานเพื่อกลับมาแก้ต่อหรือส่งออกภาพและวิดีโอ'],
    tools:['Tools on your canvas','แถบซ้ายใช้เลือก ย้าย หมุนดาว เพิ่มข้อความ Focus และวาด แถบขวาใช้เพิ่ม Shapes / Kit และ Undo / Redo แตะไอคอนเพื่อเปิดเมนูย่อย; ลากที่หูจับเพื่อย้ายแถบ'],
    design:['Design & Kits','เลือกเลเยอร์ก่อนเปิด Design จึงปรับได้เฉพาะชิ้นนั้น ค่าที่ถูกล็อกต้องปลดล็อกก่อน ข้อความ: เลือกช่วงตัวอักษรก่อนเปลี่ยนสีเพื่อใช้หลายสีในข้อความเดียว'],
    tune:['Tune the core','Tune แก้ดาวที่กำลังเลือก Cerebra และดาวอื่นมีตัวเลือกต่างกัน เมื่อ Hide subject หรือปิด Network ค่าที่เกี่ยวข้องจะถูกล็อกจนเปิดกลับ Surface แต่ละโหมดมีชุดค่าปรับเฉพาะของตน'],
    effects:['Effects & focus','เลือกเอฟเฟกต์แล้วปรับความแรง Focus ใช้รูปวงกลม สี่เหลี่ยม หรือสามเหลี่ยมกำหนดพื้นที่เบลอ: เบลอด้านใน ด้านนอก หรือเฉพาะรูปทรง สามารถเลือกให้ข้อความและวัตถุรับผลเบลอได้'],
    water:['Water Lab','กด Lab เพื่อเปิดแถบ Water Lab บน Canvas เลือกเครื่องมือแล้วลากบนภาพ เครื่องมือวาดน้ำแยกจาก Draw ของ Studio ค่าภาพ ฟิสิกส์ Current การชนกับดาว และ Particle Flow อยู่ในเมนู Lab'],
    layers:['Layers & motion','เลเยอร์บนอยู่หน้ากว่าเลเยอร์ล่าง จัดกลุ่มเพื่อย้ายหรือใช้ Group motion ร่วมกัน Lock ป้องกันการแก้ไข Hide ซ่อนจากภาพ Solo แสดงเฉพาะที่ต้องการ Motion พับไว้เมื่อไม่ได้ใช้งาน'],
    save:['Save & export','Save project เก็บไฟล์ที่แก้ต่อได้ Export image / video เป็นผลลัพธ์ภาพหรือวิดีโอ Save to Library เก็บงานในเบราว์เซอร์นี้ งานส่วนตัวไม่ได้ซิงก์ข้ามเครื่อง: Save project เพื่อย้ายงาน และ Export Library เพื่อสำรองชุดงาน'],
    menus:['The top menu bar','แถบบนเปิดเครื่องมือเดียวกับแถบใน Canvas เมนูที่ต้องมีการเลือกเลเยอร์จะเปิดใช้งานเมื่อเลือกชนิดที่ถูกต้อง และปลด Lock แล้ว Window ใช้แสดงหรือซ่อนแถบเมนู']
  };
  // Explain what changes, then the exact control type/range/options from the application.
  const meanings = [
    [/viscosity/i,'ความหนืดของน้ำ: ค่าสูงไหลช้าลงและจับตัวมากขึ้น'],[/vorticity|curl/i,'ความแรงของการหมุนวนหรือความโค้งของเส้น; ค่าสูงเพิ่มความปั่นป่วน'],[/dissipation|retention/i,'การคงสีของน้ำ: ใกล้ 1 สีอยู่ได้นานขึ้น'],[/cohesion|tension|adhesion|stick/i,'แรงยึดเกาะของน้ำหรือผิว: เพิ่มเพื่อให้น้ำจับตัวหรือติดผิวมากขึ้น'],[/collision|collide|impact|bounce/i,'การตอบสนองเมื่อชน: เปิดการชนก่อนปรับแรงเด้งและการกระจาย'],[/stain/i,'สีที่ติดผิวดาว; อายุ 0 เก็บรอยไว้จนกว่าจะล้าง'],[/suction|absorb/i,'แรงดูดหรือการรับสีจากน้ำของอนุภาค'],[/opacity|alpha/i,'ความทึบ: ค่าสูงเห็นชัด ค่าต่ำโปร่งใส'],[/blur|softness/i,'ความเบลอหรือความนุ่มของขอบ: เพิ่มเพื่อให้ฟุ้งขึ้น'],[/shadow/i,'เงาของดาวหรือวัตถุ: ปรับความเข้มและความนุ่มของเงา'],[/light|bright|glow|bloom/i,'แสงและความสว่าง: เพิ่มเพื่อให้สว่างขึ้น; ค่าสูงอาจลดรายละเอียดส่วนสว่าง'],[/font|typeface/i,'ตระกูลฟอนต์ของข้อความ; ชื่อดาวเลือกแยกรายดาวหรือใช้ Label font ร่วมกันได้'],[/weight/i,'น้ำหนักตัวอักษร: Regular บางกว่า Bold'],[/label distance|offset|spacing|gap/i,'ระยะห่างหรือตำแหน่ง: เพิ่มเพื่อเว้นพื้นที่มากขึ้น'],[/name|title|caption|subtitle|text|content/i,'ข้อความที่แสดงในชิ้นงาน: พิมพ์ในช่องนี้; ชื่อดาวแยกช่องรายดาวและใส่จุลภาคในชื่อได้'],[/colour|color|palette/i,'สีขององค์ประกอบนี้: แตะช่องสีเพื่อเลือก หรือใช้ Eyedropper ที่เมนูนั้น'],[/spin|rotation|rotate|angle|tilt|roll/i,'มุมหรือความเร็วหมุน: ค่าเป็นลบกลับทิศ; เปิด Spin / Motion ก่อนปรับค่าที่ขึ้นกับการเคลื่อนไหว'],[/speed|rate|time scale/i,'ความเร็วของการเคลื่อนไหว: ค่าสูงเคลื่อนเร็วขึ้น'],[/freeze|paused/i,'หยุดการเคลื่อนไหวชั่วคราวโดยไม่ลบองค์ประกอบ'],[/size|radius|width|height|scale|thickness/i,'ขนาดหรือความหนาของส่วนนี้: เพิ่มเพื่อให้ใหญ่หรือหนาขึ้น'],[/count|density|bodies|rows|columns|marks|ticks|copies|segments/i,'จำนวนหรือความหนาแน่น: เพิ่มเพื่อให้มีองค์ประกอบมากขึ้น; จำนวนมากใช้พลังประมวลผลเพิ่ม'],[/duration|lifetime|cycle|loop/i,'ระยะเวลาหรือรูปแบบการวนซ้ำ: ปรับเพื่อจัดจังหวะและใช้ Loop check ตรวจรอยต่อ'],[/mirror|symmetry/i,'ทำซ้ำฝีแปรงแบบสมมาตรหรือสะท้อน; ปิดเมื่ออยากวาดครั้งเดียว'],[/trail|ribbon|length/i,'ความยาวของเส้นหรือรอยตามการเคลื่อนไหว'],[/grain/i,'เม็ดฟิล์มของภาพ: เพิ่มเพื่อให้พื้นผิวมีรายละเอียดแบบฟิล์ม'],[/network|links/i,'การเชื่อมต่อเส้นระหว่างจุด: เปิด Network ก่อนปรับค่าที่เกี่ยวข้อง'],[/clip|cut-out/i,'ตัดหรือซ่อนส่วนขององค์ประกอบตามรูปทรง; ไม่ลบงานต้นฉบับ'],[/reset/i,'คืนค่าในขอบเขตที่ระบุ อ่านชื่อ Reset ให้ตรงกับส่วนที่ต้องการ'],[/seed|shuffle|random/i,'สุ่มรูปแบบ: Seed เดิมให้รูปแบบเดิม; Shuffle สร้างแบบใหม่'],[/position|align|anchor|pivot|follow/i,'ตำแหน่ง จุดหมุน หรือการจัดแนวขององค์ประกอบ'],[/motion|drift|sway|pulse|breath/i,'รูปแบบหรือความแรงของการเคลื่อนไหว; เปิด Motion แล้วลองปรับค่าทีละส่วน']
  ];
  function explain(label, type, cfg = {}) {
    const meaning = meanings.find(([test]) => test.test(label))?.[1] || `ปรับ ${label} ขององค์ประกอบในเมนูนี้ แล้วดูผลบน Canvas ก่อนบันทึก`;
    const control = type === 'range' ? `ลากสไลด์ ${cfg.min}–${cfg.max}${cfg.step ? ` ทีละ ${cfg.step}` : ''}${cfg.unit ? ` ${cfg.unit}` : ''}` : type === 'select' ? `เลือก: ${(cfg.opts || []).map(o => Array.isArray(o) ? o[1] : o).join(' / ')}` : ['toggle','checkbox','check'].includes(type) ? 'แตะเพื่อเปิด / ปิด' : type === 'color' ? 'แตะช่องสีเพื่อเลือกสี' : ['text','area','textarea','bodyLabels'].includes(type) ? 'พิมพ์หรือแก้ข้อความในช่องที่ระบุ' : 'กดเมื่อต้องการใช้คำสั่งนี้';
    return `${meaning} ${control}${cfg.when ? ` แสดงเมื่อ ${cfg.when[0]} = ${[].concat(cfg.when[1]).join(' / ')}` : ''}`;
  }
  function boot() {
    const a = window.__cerebra, s = a?.studio, e = a?.entry;
    if (!e || !s?.referenceDesign || !window.__cerebraS9?.uiReady) { setTimeout(boot, 180); return; }
    if (e.launchPaths) return;
    const css = document.createElement('style'); css.textContent = `
      .cl-page{--cl-display:"Bebas Neue","Barlow Condensed",sans-serif;--cl-body:"Barlow","Noto Sans Thai",Tahoma,system-ui,sans-serif;--cl-mono:"Geist Mono",monospace;--cl-bg:#10131e;--cl-ink:#f3f1f4;--cl-muted:#b5bed2;--cl-line:#354054;--cl-pink:#ec7ba8;position:fixed;inset:0;width:100vw;max-width:none;height:100dvh;max-height:none;margin:0;padding:0;border:0;background:var(--cl-bg);color:var(--cl-ink);overflow:auto;overscroll-behavior:contain;font:16px/1.6 var(--cl-body);box-sizing:border-box;touch-action:pan-y;pointer-events:auto}
      .cl-page::backdrop{background:#10131e}.cl-page[open]{display:block}.cl-page *{box-sizing:border-box}.cl-page [hidden]{display:none!important}.cl-page svg{width:26px;height:26px;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round;flex-shrink:0}.cl-page button,.cl-page input{font:inherit}.cl-page button{cursor:pointer;color:inherit;min-height:44px}.cl-page button:focus-visible,.cl-page input:focus-visible,.cl-page summary:focus-visible{outline:2px solid var(--cl-pink);outline-offset:4px}
      .cl-shell{max-width:1200px;margin:auto;padding:30px 40px 44px}.cl-head{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between;margin-bottom:30px}.cl-brand{font:500 15px var(--cl-mono);letter-spacing:.28em}.cl-back{display:flex;align-items:center;gap:10px;padding:0;background:none;border:0;color:var(--cl-muted)!important}.cl-back svg{width:22px;transform:rotate(180deg)}
      .cl-hero{min-height:clamp(230px,calc(100dvh - 575px),320px);position:relative;display:flex;align-items:center;isolation:isolate}.cl-hero h1{font:400 clamp(64px,8vw,108px)/.98 var(--cl-display);margin:0;letter-spacing:.01em;position:relative;z-index:1;max-width:450px}.cl-art{position:absolute;right:-40px;top:-74px;width:68%;height:450px;object-fit:cover;object-position:center;mask-image:linear-gradient(90deg,transparent,#000 18%),linear-gradient(0deg,transparent,#000 20%);mask-composite:intersect;opacity:.94;pointer-events:none}.cl-orbit{position:absolute;right:0;top:15%;width:60%;height:55%;border:1px solid #ec7ba85c;border-radius:50%;transform:rotate(-20deg);pointer-events:none;z-index:1}.cl-orbit:after{content:'';position:absolute;width:7px;height:7px;background:var(--cl-pink);border-radius:50%;top:12%;left:17%;box-shadow:0 0 16px #ec7ba8}
      .cl-paths{position:relative;z-index:2;display:grid;gap:12px;margin-top:24px}.cl-path{display:flex;align-items:center;gap:30px;width:100%;text-align:left;border:1px solid var(--cl-line);border-radius:4px;background:#10131eeb;padding:24px 26px;transition:background .2s,border-color .2s,transform .2s}.cl-path:hover{background:#1b2030;border-color:var(--cl-pink);transform:translateX(3px)}.cl-path:active{transform:scale(.99)}.cl-num{font:300 30px var(--cl-mono);width:64px;border-right:1px solid var(--cl-line);color:var(--cl-muted)}.cl-symbol{color:var(--cl-pink);width:40px;display:grid;place-items:center}.cl-symbol svg{width:36px;height:36px}.cl-path strong{display:block;font:400 35px/1.2 var(--cl-display);letter-spacing:.02em}.cl-path small{display:block;margin-top:6px;color:var(--cl-muted);font:12px/1.5 var(--cl-mono);letter-spacing:.03em}.cl-path>.cl-arrow{margin-left:auto;color:var(--cl-pink)}
      .cl-guide-head{display:flex;align-items:center;justify-content:space-between;gap:24px;margin:34px 0 24px}.cl-guide-head h1{font:400 64px/1.1 var(--cl-display);margin:0}.cl-guide-head p{color:var(--cl-muted);margin:6px 0 0;letter-spacing:.04em}.cl-search{width:min(360px,100%);padding:12px 16px;background:#191e2e;color:var(--cl-ink);border:1px solid var(--cl-line);border-radius:6px}.cl-guide-layout{display:grid;grid-template-columns:220px minmax(0,1fr);gap:28px}.cl-chapters{display:flex;flex-direction:column;gap:4px;border-right:1px solid var(--cl-line);padding-right:18px;align-self:start;position:sticky;top:16px}.cl-chapters button{text-align:left;border:0;border-left:4px solid transparent;padding:10px 14px;background:none;color:var(--cl-muted)}.cl-chapters button[aria-current=true]{background:#191e2e;border-color:var(--cl-pink);color:var(--cl-pink)}.cl-content{min-width:0}.cl-content h2{font:400 34px/1.2 var(--cl-display);letter-spacing:.02em;margin:20px 0 10px}.cl-intro{color:var(--cl-muted);line-height:1.8;margin:0 0 20px}.cl-toolbar{display:flex;align-items:center;gap:12px;border:1px solid var(--cl-line);border-radius:6px;padding:16px;overflow:auto}.cl-toolbar span{display:flex;flex-direction:column;align-items:center;gap:7px;min-width:54px;color:var(--cl-muted);font-size:11px;white-space:nowrap}.cl-toolbar svg{width:26px;height:26px;color:var(--cl-ink)}.cl-steps{display:grid;gap:0}.cl-step{display:flex;align-items:center;gap:20px;padding:20px 0;border-bottom:1px solid var(--cl-line)}.cl-step-visual{width:110px;min-width:110px;height:72px;background:#191e2e;border:1px solid var(--cl-line);border-radius:6px;display:flex;align-items:center;justify-content:center;overflow:hidden;color:var(--cl-pink)}.cl-step-visual img{width:100%;height:100%;object-fit:cover}.cl-step-visual svg{width:40px;height:40px}.cl-step strong{font:400 25px var(--cl-display)}.cl-step p{margin:4px 0 0;color:var(--cl-muted);font-size:14px}.cl-enter{display:flex;align-items:center;justify-content:center;gap:14px;width:100%;margin-top:24px;padding:12px;border:1px solid var(--cl-pink);border-radius:5px;background:none;color:var(--cl-pink)!important;letter-spacing:.08em;font:14px var(--cl-mono)!important}.cl-enter:hover{background:#ec7ba815}
      .cl-topic{border-bottom:1px solid var(--cl-line);padding:10px 0}.cl-topic summary{display:flex;align-items:center;gap:12px;cursor:pointer;list-style:none;min-height:44px;font:500 17px/1.5 var(--cl-body)}.cl-topic summary:after{content:'+';color:var(--cl-pink);margin-left:auto}.cl-topic[open] summary:after{content:'−'}.cl-topic summary svg{width:24px;height:24px;color:var(--cl-pink)}.cl-topic summary img{width:42px;height:42px;object-fit:contain}.cl-topic p{color:var(--cl-muted);line-height:1.8;margin:12px 0}.cl-location{display:block;font:11px/1.6 var(--cl-mono);color:var(--cl-pink);margin:8px 0}.cl-params{margin:12px 0;display:grid;gap:12px}.cl-param{padding:10px 14px;background:#191e2e;border-radius:4px}.cl-param dt{font-weight:500}.cl-param dd{margin:6px 0 0;color:var(--cl-muted);font-size:14px;line-height:1.8}.cl-empty{color:var(--cl-muted);padding:30px 0}.cl-result-count{color:var(--cl-muted);font-size:13px;margin:0 0 12px}
      @media(min-width:761px) and (min-height:850px){.cl-shell{padding-top:44px}.cl-art{height:510px}}
      @media(max-width:760px){.cl-shell{padding:22px 22px max(30px,env(safe-area-inset-bottom))}.cl-head{margin-bottom:20px}.cl-brand{font-size:12px;letter-spacing:.2em}.cl-back{font-size:14px}.cl-hero{min-height:270px;align-items:flex-end;padding-bottom:18px}.cl-hero h1{font-size:64px;max-width:240px}.cl-art{width:100%;height:320px;right:-22px;top:-30px;opacity:.8}.cl-orbit{width:78%;height:45%;top:17%}.cl-paths{margin-top:12px;gap:10px}.cl-path{padding:18px 16px;gap:14px}.cl-num{width:44px;font-size:21px}.cl-symbol{width:25px}.cl-symbol svg{width:25px;height:25px}.cl-path strong{font-size:28px}.cl-path small{font:11px/1.6 var(--cl-body);letter-spacing:0}.cl-path>.cl-arrow{width:20px}.cl-guide-head{display:block;margin:22px 0}.cl-guide-head h1{font-size:48px}.cl-guide-head p{font-size:14px}.cl-search{margin-top:18px;width:100%;font-size:16px}.cl-guide-layout{display:block}.cl-chapters{position:static;flex-direction:row;overflow:auto;border-right:0;border-bottom:1px solid var(--cl-line);padding:0 0 10px;margin-bottom:18px;gap:4px}.cl-chapters button{flex:0 0 auto;font-size:14px;border-left:0;border-bottom:3px solid transparent;padding:8px 12px}.cl-content h2{font-size:30px}.cl-intro{font-size:15px}.cl-toolbar{padding:12px;gap:8px}.cl-step{gap:14px}.cl-step-visual{width:76px;min-width:76px;height:64px}.cl-topic summary{font-size:16px}.cl-param{padding:10px}.cl-shell{overflow-wrap:break-word}}
      @media(prefers-reduced-motion:reduce){.cl-path{transition:none}.cl-path:hover{transform:none}}
    `; document.head.append(css);
    const page = document.createElement('dialog'); page.className='cl-page';page.setAttribute('aria-label','Cerebra paths and guide');
    page.innerHTML=`<div class="cl-shell"><header class="cl-head"><span class="cl-brand">CEREBRA</span><button type="button" class="cl-back" data-cl-back>${arrow}<span>Back</span></button></header><section data-cl-hub><div class="cl-hero"><img class="cl-art" data-cl-art alt="" hidden><div class="cl-orbit" aria-hidden="true"></div><h1>Choose<br>your path</h1></div><nav class="cl-paths" aria-label="Choose your path">${[['studio','Studio','Create your composition',s.el.querySelector('[data-studio-tool="move"] svg')?.outerHTML||arrow],['guide','How to use','Tools, controls & export',book],['planets','Explore planets','Find a world before creating',orbit]].map(([id,title,sub,icon],i)=>`<button type="button" class="cl-path" data-cl-path="${id}"><span class="cl-num">0${i+1}</span><span class="cl-symbol">${icon}</span><span><strong>${title}</strong><small>${sub}</small></span><span class="cl-arrow">${arrow}</span></button>`).join('')}</nav></section><section data-cl-guide hidden><div class="cl-guide-head"><div><h1>How to use</h1><p>Your guide to the Studio</p></div><input type="search" class="cl-search" data-cl-search placeholder="Find a tool or setting" aria-label="Find a tool or setting"></div><div class="cl-guide-layout"><nav class="cl-chapters" aria-label="Guide chapters">${chapters.map(([id,label])=>`<button type="button" data-cl-chapter="${id}" aria-current="${id==='start'}">${label}</button>`).join('')}</nav><div class="cl-content" data-cl-content></div></div></section></div>`;
    document.body.append(page);
    let chapter='start', topics=[], guideOrigin='hub', direct=false, hero='', searchTimer, pressedButton=null;
    // Opening on touch release must not activate a newly revealed button under that finger.
    page.addEventListener('pointerdown',ev=>{pressedButton=ev.target.closest('button');},true);
    page.addEventListener('pointercancel',()=>{pressedButton=null;});
    page.addEventListener('click',ev=>{const button=ev.target.closest('button');if(ev.detail>0&&button&&button!==pressedButton){ev.preventDefault();ev.stopImmediatePropagation();}pressedButton=null;},true);
    const svg = selector => document.querySelector(selector)?.querySelector('svg')?.outerHTML || '';
    const toolbar = root => `<div class="cl-toolbar" aria-label="${esc(root.getAttribute('aria-label')||'Studio toolbar')}">${[...root.querySelectorAll('button')].filter(b=>!b.hasAttribute('data-tray-grip')&&!b.hasAttribute('data-dock-fold')).map(b=>`<span>${b.querySelector('svg')?.outerHTML||''}${esc(b.getAttribute('aria-label')||b.textContent.trim())}</span>`).join('')}</div>`;
    function art() {
      if(hero || !a.worldsReady || a.cap)return;
      const source=a.orrery.worlds.find(w=>w.def.id==='Inferno')||a.orrery.worlds[0];if(!source?.model)return;
      const r=a.stage.renderer,dpr=r.getPixelRatio(),scene=new THREE.Scene(),model=source.model.clone(true),materials=[];
      model.traverse(o=>{if(o.isMesh){o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();materials.push(...[].concat(o.material));o.visible=true;}});
      model.rotation.set(-.15,.65,-.18);scene.add(model);scene.add(new THREE.HemisphereLight('#ffd5f0','#191527',3));const light=new THREE.DirectionalLight('#ffe6cf',5);light.position.set(-3,4,5);scene.add(light);
      const camera=new THREE.PerspectiveCamera(35,1000/750,.01,100);camera.position.set(0,0,source.def.radius*3.7);camera.lookAt(0,0,0);
      try{r.setPixelRatio(1);r.setSize(1000,750,false);r.render(scene,camera);hero=r.domElement.toDataURL('image/png');const image=page.querySelector('[data-cl-art]');image.src=hero;image.hidden=false;}catch(err){console.warn('Launch planet preview unavailable',err);}finally{r.setPixelRatio(dpr);r.setSize(a.stage.width,a.stage.height,false);materials.forEach(m=>m.dispose());}
    }
    const push=(cat,title,desc,location,icon='',params=[])=>topics.push({cat,title,desc,location,icon,params});
    function collect(root,cat,location) {
      if(!root)return;
      const seen=new Set();root.querySelectorAll('input:not([type=file]):not([type=hidden]),select,textarea,[data-cfx-sw],.tune-seg,.st-switch').forEach(input=>{
        const row=input.closest('label,.studio-control,.tune-row,.st-fly-row,.st-water-row,.cfx-row'), label=input.getAttribute('aria-label')||row?.querySelector(':scope > span,:scope > b')?.textContent.trim()||[...(row?.childNodes||[])].filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim();if(!label)return;
        const group=input.closest('details,section[data-pane],.tune-pane'),name=group?.querySelector(':scope > summary,:scope > h4,:scope > b')?.textContent.trim()||'';
        const title=name?`${name} · ${label}`:label;if(seen.has(title))return;seen.add(title);
        const type=input.hasAttribute('data-cfx-sw')||input.matches('.tune-seg,.st-switch')?'select':input.tagName==='SELECT'?'select':input.tagName==='TEXTAREA'?'area':input.type;
        push(cat,title,explain(label,type,{min:input.min,max:input.max,step:input.step,opts:input.options?[...input.options].map(o=>o.textContent):[...input.querySelectorAll('button')].map(b=>b.textContent.trim())}),location);
      });
    }
    function buildGuide(){
      topics=[];
      const tools=[['[data-studio-tool="move"]','Move','เลือกแล้วลากวัตถุหรือดาว ย่อ/ขยายจากจุดจับและหมุนจากจุดหมุน ลากพื้นที่ว่างเพื่อเลือกหลายชิ้น; V'],['[data-studio-tool="hand"]','Hand','ลากเพื่อหมุนดาวที่กำลังเลือก; H'],['[data-studio-tool="select"]','Select','ลากครอบหลายเลเยอร์ เลือก Box หรือ Lasso แล้วคลิกพื้นที่ว่างเพื่อยกเลิก; M'],['[data-studio-add="text"]','Text','เพิ่มเลเยอร์ข้อความ แตะข้อความเพื่อแก้ เปิด Design เพื่อเลือกฟอนต์ ขนาด สี และระยะตัวอักษร; T'],['[data-flyout="focus"]','Focus','เพิ่มรูปทรงกำหนดพื้นที่เบลอ เลือก Blur target และ Blur area เพื่อเบลอด้านใน ด้านนอก หรือเฉพาะรูปทรง'],['[data-flyout="draw"]','Draw & Eraser','เปิด Draw แล้วลากบน Canvas ปรับสี ขนาด แปรง และการเคลื่อนไหว Eraser ลบเส้นวาดและ Shapes ได้ แต่ไม่ลบ Kit'],['[data-flyout="decor"]','Shapes','เพิ่มวงกลม สี่เหลี่ยม หรือสามเหลี่ยมตกแต่ง แล้วเลือกชิ้นเพื่อปรับ Fill เส้นขอบ และความทึบ'],['[data-flyout="kit"]','Kit','เพิ่มกราฟิกที่แก้ไขได้ เช่น HUD วงโคจร สัญลักษณ์ กราฟ และระบบดาว เลือกชิ้นแล้วเปิด Design เพื่อแก้ค่าของ Kit นั้น'],['[data-studio-undo]','Undo / Redo','Undo ย้อนหนึ่งการแก้ไข Redo ทำสิ่งที่ย้อนกลับใหม่; Ctrl/Cmd Z และ Ctrl/Cmd Shift Z']];
      tools.forEach(([sel,title,desc])=>push('tools',title,desc,'Canvas · Tools / Decor',svg(`#studio ${sel}`)));
      const docks=[['[data-studio-tune]','Tune the core','เปิดค่าปรับของดาวที่เลือก: รูปทรง สี Surface และ Motion'],['[data-studio-fx]','Effects','เปิดเอฟเฟกต์ของ Cerebra: Surface, Network, Formation และส่วนประกอบ'],['[data-s9-entry]','Lab','เปิด Water Lab พร้อมแถบเครื่องมือวาดน้ำบน Canvas'],['[data-studio-export]','Save','เปิดการส่งออกภาพหรือวิดีโอ และบันทึกงาน'],['[data-studio-tools]','Design','เปิดฉาก: Presets, Background, Lighting, Focus, Motion และ Layout'],['[data-studio-lib]','Library','เปิดคลังงาน เลื่อนแนวนอนด้วยแถบสไลด์หรือลูกกลิ้งบน PC เลือก Open เพื่อแก้ต่อ']];
      docks.forEach(([sel,title,desc])=>push('tools',title,desc,'Bottom toolbar',svg(`#studio ${sel}`)));
      collect(s.panel,'design','Design · bottom toolbar');collect(s.ctx,'design','Select layer → Design');
      s.el.querySelectorAll('[data-fly]').forEach(f=>collect(f,['focus'].includes(f.dataset.fly)?'effects':['kit','kitdesign','textdesign','style'].includes(f.dataset.fly)?'design':'tools',`Canvas · ${f.querySelector('.st-fly-title')?.textContent||f.dataset.fly}`));
      Object.entries(KIT).forEach(([key,def])=>{const button=s.el.querySelector(`[data-studio-kit="${key}"]`),canvas=button?.querySelector('canvas');let icon='';try{if(canvas)icon=`<img src="${canvas.toDataURL()}" alt="">`;}catch{}
        push('design',`Kit · ${def.label}`,'เพิ่มจาก Kit แล้วเลือกชิ้นบน Canvas เพื่อเปิด Design ค่าด้านล่างแก้เฉพาะ Kit ที่เลือก Motion เปิดก่อนปรับการเคลื่อนไหว','Canvas → Kit → select → Design',icon,def.ui.map(u=>({label:u.label,desc:explain(u.label,u.t,u)})));
      });
      collect(document.getElementById('tune'),'tune','Tune the core');collect(document.getElementById('wtune'),'tune','Tune world');
      Effects.list.forEach(fx=>push('effects',fx.title||fx.label||fx.name||fx.id,'เปิดเอฟเฟกต์นี้ก่อนปรับค่าที่เกี่ยวข้อง เลือก Surface style หรือโหมดที่รองรับเพื่อเห็นผล','Effects / Tune', '', (fx.controls||[]).map(c=>({label:c.label,desc:explain(c.label,c.type||'range',{...c,opts:c.options})}))));
      collect(s.fxBox,'effects','Effects');collect(s.el.querySelector('.st-s9-panel'),'water','Lab → Water Lab');collect(s.el.querySelector('.st-water-quick'),'water','Canvas → Water toolbar');
      s.el.querySelectorAll('[data-water-tool]').forEach(b=>{const label=b.textContent.trim();if(topics.some(t=>t.cat==='water'&&t.title===label))return;const help={paint:'ลากเพื่อวาดน้ำตามสีและขนาดแปรง',drop:'แตะเพื่อวางน้ำเป็นจุด',ripple:'แตะเพื่อสร้างคลื่นน้ำ',pour:'ลากเพื่อเทน้ำต่อเนื่อง',tentacle:'ลากเพื่อวาดริบบอนน้ำ; ปรับ Ribbon length และ sway',stretch:'ลากน้ำเดิมเพื่อดันหรือดึง',eraser:'ลากลบน้ำ ไม่ลบข้อความหรือวัตถุ Studio',picker:'แตะเพื่อเก็บสีจากน้ำมาใช้กับแปรง'};push('water',label,`${help[b.dataset.waterTool]||'เลือกเครื่องมือแล้วลากบน Canvas'} ปรับ Brush size และสีใน Water Lab`,'Lab · tools',b.querySelector('svg,span[aria-hidden]')?.outerHTML||'');});
      [['Groups','สร้าง New group แล้วย้ายเลเยอร์เข้า Group พับกลุ่มเพื่อลดความรก Lock / Hide ที่ระดับกลุ่มมีผลกับสมาชิก'],['Solo','แสดงเฉพาะเลเยอร์ที่เลือก กดอีกครั้งกลับมาแสดงงานทั้งหมด'],['Selection workflow','Align จัดแนว Distribute เว้นระยะเท่ากัน Pivot เปลี่ยนจุดหมุน Group motion ใช้การเคลื่อนไหวร่วมกัน'],['Timeline & keyframes','เลือกเลเยอร์ ไปยังเวลา เพิ่ม Keyframe ปรับตำแหน่ง ขนาด หมุน และความทึบ แล้ว Play เพื่อดูภาพเคลื่อนไหว'],['Loop check','ดูรอยต่อช่วงต้นและท้ายของ Timeline ก่อนบันทึกวิดีโอวนซ้ำ'],['Library Spotlight','ใช้ลูกศรชมตัวอย่าง กด Open work เพื่อแก้ต่อ Next เปิดขั้นตอนสอน กากบาทปิด และ Don’t show again ซ่อนครั้งถัดไป']].forEach(([t,d])=>push('layers',t,d,'Layers / Design → Motion / More → Workflow'));
      collect(s.timelineSection,'layers','Design → Motion timeline');collect(s.el.querySelector('.st-workflow'),'layers','More → Selection workflow');
      [['Save project (.cerebra)','File → Save project: ดาวน์โหลดไฟล์เก็บดาว เลเยอร์ และค่าปรับเพื่อแก้ต่อบนเครื่องอื่น เปิดคืนจาก File → Open project'],['Save to Library','เก็บชิ้นงานในเบราว์เซอร์ที่ใช้อยู่ เปิดกลับจาก Library การล้างข้อมูลเบราว์เซอร์อาจลบงานส่วนตัว จึงควร Save project สำรอง'],['Export Library','ดาวน์โหลดชุดงานส่วนตัวเป็นไฟล์ JSON สำรอง หากต้องการเปิดแก้บนอีกเครื่อง ใช้ Save project ของแต่ละงานและ File → Open project'],['Export image','Save → เลือก PNG / JPEG / WebP / PDF และขนาด 1×, 2× หรือ 3× แล้วกด Download'],['Record video','Save → เลือก Video ปรับเวลา ความละเอียด จากนั้น Record ระบบเลือกชนิดไฟล์ที่เบราว์เซอร์รองรับให้อัตโนมัติ รอจนจบ หลีกเลี่ยงเปลี่ยนแท็บระหว่างบันทึก'],['Save planet','Save planet เก็บรูปลักษณ์ของดาว ต่างจาก Save project ที่เก็บทั้งองค์ประกอบ Studio'],['Undo before reset','Reset คืนค่าตามขอบเขตที่ระบุ ถ้าไม่ต้องการผลลัพธ์ให้ Undo ทันที; Save project ก่อนเริ่มแก้ชุดใหญ่']].forEach(([t,d])=>push('save',t,d,'File / Bottom toolbar → Save',svg('#studio [data-studio-export]')));
      collect(s.el.querySelector('.st-save'),'save','Save → export options');
      [[s.panel,'design','Design'],[s.ctx,'design','Selected layer'],[document.getElementById('tune'),'tune','Tune the core'],[document.getElementById('wtune'),'tune','Tune world'],[s.fxBox,'effects','Effects'],[s.el.querySelector('.st-s9-panel'),'water','Water Lab'],[s.el.querySelector('.st-save'),'save','Save']].forEach(([root,cat,loc])=>root?.querySelectorAll('button').forEach(b=>{const label=b.getAttribute('aria-label')||b.textContent.trim();if(!label||label.length>90||/close|drag|collapse/i.test(label)||topics.some(t=>t.cat===cat&&t.title===label))return;push(cat,label,b.title||explain(label,'button'),loc,b.querySelector('svg')?.outerHTML||'');}));
      const commandHelp={
        'Save project…':'ดาวน์โหลดไฟล์ .cerebra เก็บข้อมูลที่แก้ต่อได้', 'Open project…':'เลือกไฟล์ .cerebra เพื่อโหลดงานและค่าปรับ', 'Save to Library':'เก็บงานในคลังของเบราว์เซอร์นี้', 'Export image / video…':'เปิด Save เพื่อเลือกชนิดภาพ ขนาด หรือระยะเวลาวิดีโอ', 'Exit Studio':'ออกจาก Studio และกลับหน้าที่เข้ามา',
        'Undo':'ย้อนการแก้ไขล่าสุด', 'Redo':'ทำการแก้ไขที่เพิ่งย้อนกลับอีกครั้ง', 'Duplicate selection':'สร้างสำเนาของเลเยอร์ที่เลือก', 'Selection workflow…':'เปิด Align, Distribute, Pivot, Group motion และ Loop check', 'Design selected…':'เปิดค่าปรับของเลเยอร์ที่เลือก; เลือก Text, Shape หรือ Kit ก่อน', 'Kit library…':'เลือกกราฟิก Kit เพื่อเพิ่มลง Canvas', 'Group selection':'สร้างกลุ่มจากเลเยอร์ที่เลือก',
        'Background & colours…':'เปิด Design เพื่อเลือกสีพื้นหลังหรือ Gradient', 'Lighting & shadow…':'เปิดความสว่าง ทิศแสง และความเข้ม/นุ่มของเงา', 'Scene presets…':'เลือกองค์ประกอบเริ่มต้นแล้วปรับต่อได้', 'New group':'สร้างกลุ่มว่างและเปิด Layers เพื่อจัดเลเยอร์', 'Group selected layers':'รวมเลเยอร์ที่เลือกให้ย้ายและปรับร่วมกัน', 'Ungroup selected layers':'นำเลเยอร์ออกจากกลุ่มเดิม', 'Lock / unlock selection':'ป้องกันการแก้ไขหรือปลดล็อกเลเยอร์', 'Hide / show selection':'ซ่อนหรือแสดงเลเยอร์ใน Canvas และผลส่งออก', 'Bring to front':'ย้ายเลเยอร์ขึ้นด้านหน้าสุด', 'Send to back':'ย้ายเลเยอร์ไปด้านหลังสุด', 'Delete selected layers':'ลบเลเยอร์ที่เลือก; ใช้ Undo ถ้าลบผิด',
        'Add text':'เพิ่มข้อความหนึ่งเลเยอร์', 'Edit selected text…':'แก้เนื้อหาของข้อความที่เลือก', 'Typography & style…':'ปรับฟอนต์ ขนาด น้ำหนัก สี ระยะตัวอักษร และสไตล์', 'Select all objects':'เลือกวัตถุที่แก้ไขได้ทั้งหมด', 'Deselect':'ยกเลิกการเลือกและกรอบครอบ', 'Box selection':'ลากกรอบสี่เหลี่ยมครอบเลเยอร์', 'Lasso selection':'ลากเส้นอิสระรอบเลเยอร์ที่ต้องการ',
        'Colour effects…':'เปิดชุดเอฟเฟกต์สีแล้วปรับ Amount', 'Focus & blur…':'เปิดรูปทรง Focus และการเบลอด้านใน/นอกหรือเฉพาะรูป', 'Film grain & lens…':'ปรับเม็ดฟิล์ม ความคลาดสี และเอฟเฟกต์ Lens', 'Object motion / keyframes…':'เปิด Timeline เพื่อสร้างและเล่น Keyframes', 'Group motion / loop check…':'เปิดการเคลื่อนไหวร่วมกันและตรวจรอยต่อวนซ้ำ', 'Show interface':'แสดงหรือซ่อนเครื่องมือเพื่อดูชิ้นงาน', 'Canvas grid':'เปิด/ปิดเส้น Grid', 'Smart guides':'เปิดเส้นช่วยจัดแนวเมื่อเลื่อนวัตถุ', 'Snap to objects':'ดูดตำแหน่งเข้าหาวัตถุเพื่อจัดแนว', 'Reset menu positions':'คืนตำแหน่งแถบเครื่องมือที่ลากย้าย',
        'Tools':'เปิด/ปิดแถบย้าย เลือก ข้อความ Focus และ Draw', 'Decor tools':'เปิด/ปิดแถบ Shapes, Kit, Undo และ Redo', 'Layers':'เปิด/ปิดรายการเลเยอร์และกลุ่ม', 'Design':'เปิด/ปิดค่าปรับฉาก', 'Bottom toolbar':'เปิด/ปิดแถบเมนูด้านล่าง', 'Motion timeline':'เปิด/ปิด Timeline', 'Layout & guides':'เปิด Align, Snap และค่าการจัดวาง', 'Library':'เปิด/ปิดคลังผลงาน', 'Tune the core':'เปิด/ปิดค่าปรับของดาวที่เลือก', 'How to use…':'เปิดคู่มือนี้และกลับ Studio ได้ทันที', 'Keyboard shortcuts…':'แสดงตารางคีย์ลัดของโปรแกรม', 'Timeline guide':'เปิดส่วน Timeline พร้อมคำแนะนำ', 'Layout & snapping guide':'เปิดคำแนะนำการจัดแนวและการดูดตำแหน่ง'
      };
      const menuHelp={File:'บันทึก เปิดไฟล์ เก็บ Library ส่งออก และออกจาก Studio',Edit:'ย้อน/ทำซ้ำ คัดลอก เลือก Design / Kit และจัดกลุ่ม',Image:'พื้นหลัง สี แสง เงา Presets และส่งออกภาพ',Layer:'สร้างกลุ่ม ย้ายลำดับ ซ่อน ล็อก และลบเลเยอร์',Type:'เพิ่มหรือแก้ข้อความ และ Typography ของข้อความที่เลือก',Select:'เลือกทั้งหมด ยกเลิกเลือก Box และ Lasso',Filter:'เอฟเฟกต์สี Focus เม็ดฟิล์ม Lens และ Motion',View:'แสดง UI Grid Guides Snap และคืนตำแหน่งเมนู',Window:'เปิด/ปิด Tools Decor Layers Design Dock Timeline Library และ Tune',Help:'คู่มือการใช้งาน คีย์ลัด Timeline และ Layout'};
      Object.entries(s.menuEntries||{}).forEach(([name,fn])=>push('menus',name,menuHelp[name]||name,'Top menu bar','',fn().map(([label,,checked,keys,disabled])=>({label,desc:`${commandHelp[label]||menuHelp[name]}${keys?` คีย์ลัด ${keys}`:''}${disabled?' ต้องเลือกเลเยอร์ที่รองรับหรือปลดล็อกก่อน':''}`}))));
      (s.SHORTCUTS||[]).forEach(k=>push('tools',`Shortcut · ${k.label}`,`กด ${s.keyLabel(k)} เมื่อทำงานใน Canvas; ขณะพิมพ์ข้อความจะใช้คีย์ของช่องข้อความก่อน`,`Keyboard · ${k.group}`));
    }
    function renderGuide(){
      const query=page.querySelector('[data-cl-search]').value.trim().toLocaleLowerCase(),content=page.querySelector('[data-cl-content]');
      page.querySelectorAll('[data-cl-chapter]').forEach(b=>b.setAttribute('aria-current',String(!query&&b.dataset.clChapter===chapter)));
      const relevant=topics.filter(t=>query?`${t.title} ${t.desc} ${t.location} ${t.params.map(p=>p.label+' '+p.desc).join(' ')}`.toLocaleLowerCase().includes(query):t.cat===chapter);
      if(!query&&chapter==='start'){
        content.innerHTML=toolbar(s.el.querySelector('[data-tray="add"]'))+`<h2>${intros.start[0]}</h2><p class="cl-intro">${intros.start[1]}</p><div class="cl-steps">${[['Choose a world','เริ่มจาก Cerebra หรือเลือก Explore planets เพื่อชมดาวก่อนสร้าง',hero?`<img src="${hero}" alt="Planet preview">`:orbit],['Add text & shapes','ใช้ Text, Shapes หรือ Kit แล้วเลือกชิ้นเพื่อเปิด Design ปรับฟอนต์ สี และ Motion',s.icons.text+s.icons.tri],['Save your work','Save project เพื่อแก้ต่อ หรือ Export image / video เพื่อส่งผลงาน',svg('#studio [data-studio-export]')]].map(([t,d,i],n)=>`<div class="cl-step"><div class="cl-step-visual" aria-hidden="true">${i}</div><div><strong>${n+1} · ${t}</strong><p>${d}</p></div></div>`).join('')}</div><button type="button" class="cl-enter" data-cl-studio>${svg('#studio [data-studio-tool="move"]')}Enter Studio</button>`;
      }else{
        const head=query?'Search results':intros[chapter][0],intro=query?'ค้นจากทุกบท รวมชื่อเมนู เครื่องมือ และค่าปรับ':intros[chapter][1];
        content.innerHTML=(chapter==='tools'&&!query?toolbar(s.el.querySelector('[data-tray="add"]'))+toolbar(s.el.querySelector('[data-tray="decor"]'))+toolbar(s.el.querySelector('.st-dock')):'')+`<h2>${head}</h2><p class="cl-intro">${intro}</p><p class="cl-result-count">${relevant.length} topics</p>`+(relevant.length?relevant.map(t=>`<details class="cl-topic"${query?' open':''}><summary>${t.icon}${esc(t.title)}</summary><span class="cl-location">${esc(t.location)}</span><p>${esc(t.desc)}</p>${t.params.length?`<dl class="cl-params">${t.params.filter(p=>!query||`${t.title} ${p.label} ${p.desc}`.toLocaleLowerCase().includes(query)).map(p=>`<div class="cl-param"><dt>${esc(p.label)}</dt><dd>${esc(p.desc)}</dd></div>`).join('')}</dl>`:''}</details>`).join(''):'<p class="cl-empty">ไม่พบเครื่องมือ ลองชื่อภาษาอังกฤษในเมนูหรือคำภาษาไทย เช่น สี เบลอ น้ำ</p>');
      }
      content.querySelector('[data-cl-studio]')?.addEventListener('click',enterStudio);
    }
    function showHub(){pressedButton=null;guideOrigin='hub';page.querySelector('[data-cl-hub]').hidden=false;page.querySelector('[data-cl-guide]').hidden=true;page.querySelector('[data-cl-back] span').textContent='Back';page.setAttribute('aria-label','Choose your Cerebra path');e.choice.hidden=true;document.body.classList.remove('route-choose');document.documentElement.classList.add('route-lock');document.querySelector('main').inert=true;if(!page.open)page.showModal();page.scrollTop=0;art();page.querySelector('[data-cl-path="studio"]').focus({preventScroll:true});}
    function showGuide(origin='hub'){guideOrigin=origin;chapter='start';buildGuide();page.querySelector('[data-cl-search]').value='';page.querySelector('[data-cl-hub]').hidden=true;page.querySelector('[data-cl-guide]').hidden=false;page.querySelector('[data-cl-back] span').textContent=origin==='studio'?'Back to Studio':'Back to paths';page.setAttribute('aria-label','How to use Cerebra');if(!page.open)page.showModal();renderGuide();page.scrollTop=0;page.querySelector('[data-cl-chapter="start"]').focus({preventScroll:true});}
    function enterStudio(){page.close();if(guideOrigin==='studio'&&s.active)return;direct=true;originalEnter();e.openStudio(e.S);}
    const originalLaunch=e.launch.bind(e),originalEnter=e.enter.bind(e),originalBack=e.back.bind(e),originalUpdate=e.update.bind(e),originalClose=s.close.bind(s);
    e.launch=route=>{if(route!=='atelier')return originalLaunch(route);if(e.entering||e.choice.hidden)return;if(!a.worldsReady){e.pending=true;e.choice.querySelector('[data-route-status]').hidden=false;e.choice.querySelector('[data-route-status]').textContent='Preparing the worlds…';return;}e.pending=false;e.choice.querySelector('[data-route-status]').hidden=true;showHub();};
    e.back=()=>{e.leave();showHub();};e.update=dt=>page.open?true:originalUpdate(dt);
    s.close=()=>{const was=s.active;originalClose();if(was&&direct){direct=false;e.leave();showHub();}};
    page.querySelectorAll('[data-cl-path]').forEach(b=>b.onclick=()=>{if(b.dataset.clPath==='studio')enterStudio();else if(b.dataset.clPath==='guide')showGuide();else{page.close();direct=false;originalEnter();}});
    page.querySelector('[data-cl-back]').onclick=()=>{if(!page.querySelector('[data-cl-guide]').hidden){if(guideOrigin==='studio'){page.close();s.menuBar.querySelector('[data-menu-top="Help"]')?.focus();}else showHub();}else{page.close();originalBack();}};
    page.querySelectorAll('[data-cl-chapter]').forEach(b=>b.onclick=()=>{chapter=b.dataset.clChapter;page.querySelector('[data-cl-search]').value='';renderGuide();});
    page.querySelector('[data-cl-search]').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(renderGuide,100);};
    page.addEventListener('keydown',event=>{event.stopPropagation();});page.addEventListener('cancel',event=>{event.preventDefault();page.querySelector('[data-cl-back]').click();});
    e.launchPaths={show:showHub,guide:showGuide,get topicCount(){return topics.length;},get isOpen(){return page.open;}};a.openGuide=()=>showGuide(s.active?'studio':'hub');
  }
  setTimeout(boot,0);
})();
